[project]
name = "moodle-python-apis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "docopt>=0.6.2",
    "requests==2.32.4",
]

[dependency-groups]
dev = []
